apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: backend-v3
  namespace: flux-system
spec:
  releaseName: backend-v3
  interval: 5m
  chart:
    spec:
      chart: ./charts/backend
      sourceRef:
        kind: GitRepository
        name: deployment-approval-poc
        namespace: flux-system
      interval: 5m
  targetNamespace: poc-prod
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/samuel-patrocinio/deployment-approval-poc/backend
      tag: v0.1.0
    apiPath: "0.3"
    host: poc-prod.example.com
