apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: backend-v1
  namespace: flux-system
spec:
  releaseName: backend-v1
  interval: 5m
  chart:
    spec:
      chart: ./charts/backend
      sourceRef:
        kind: GitRepository
        name: deployment-approval-poc
        namespace: flux-system
      interval: 5m
  targetNamespace: poc-prod
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/samuel-patrocinio/backend
      tag: latest
    apiPath: "0.1"
    host: poc.example.com
