name: Build

run-name: ${{ github.ref_name }}

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - app: frontend
            build-args: |
              APP_ENV=production
          - app: backend
            build-args: |
              APP_ENV=production
              API_VERSION=v2
          - app: scheduler
            build-args: |
              APP_ENV=production
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.app }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.app }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/${{ matrix.app }}:latest
          build-args: ${{ matrix.build-args }}
