name: Deploy

run-name: Deploy ${{ inputs.tag }}

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag to deploy'
        required: true
        type: string

permissions:
  contents: write
  packages: write

jobs:
  dev:
    uses: ./.github/workflows/env-deploy.yml
    with:
      environment: dev
      tag: ${{ inputs.tag }}

  qa:
    needs: dev
    uses: ./.github/workflows/env-deploy.yml
    with:
      environment: qa
      tag: ${{ inputs.tag }}

  uat:
    needs: qa
    uses: ./.github/workflows/env-deploy.yml
    with:
      environment: uat
      tag: ${{ inputs.tag }}

  prod:
    needs: uat
    uses: ./.github/workflows/env-deploy.yml
    with:
      environment: prod
      tag: ${{ inputs.tag }}
