image:
  repository: hello-world
  tag: latest
  pullPolicy: IfNotPresent

secrets:
  pullSecret: ""

cronjobs:
  cronjob1:
    enabled: true
    schedule: "*/10 * * * *"
    concurrencyPolicy: Forbid
    backoffLimit: 2
    ttlSecondsAfterFinished: 100
    startingDeadlineSeconds: 100
    resources:
      requests:
        cpu: "20m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
  cronjob2:
    enabled: true
    schedule: "55 * * * *"
    concurrencyPolicy: Forbid
    backoffLimit: 2
    ttlSecondsAfterFinished: 100
    startingDeadlineSeconds: 100
    resources:
      requests:
        cpu: "20m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
