apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: backend-v2
  namespace: flux-system
spec:
  releaseName: backend-v2
  interval: 5m
  chart:
    spec:
      chart: ./charts/backend
      sourceRef:
        kind: GitRepository
        name: deployment-approval-poc
        namespace: flux-system
      interval: 5m
  targetNamespace: poc-uat
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/samuel-patrocinio/backend
      tag: latest
    apiPath: "0.2"
    host: poc-uat.example.com
    ingress:
      swagger:
        enabled: true
